server:
  port: 8083

spring:
  application:
    name: cliente-cassandra
  data:
    cassandra:
      contact-points: localhost
      port: 9042
      keyspace-name: clientes_keyspace
      schema-action: create_if_not_exists

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6070/eureka
