server:
  port: 8083

spring:
  application:
    name: cliente-cassandra
  data:
    cassandra:
      contact-points: prod-cassandra-server
      port: 9042
      keyspace-name: clientes_keyspace
      schema-action: validate

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6071/eureka
