server:
  port: 8081

spring:
  application:
    name: cliente-mysql
  datasource:
    url: jdbc:mysql://prod-db-server:3306/clientes_db
    username: prod_user
    password: prod_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka
