server:
  port: 8084

spring:
  application:
    name: cliente-consumer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7071/eureka

spring:
  cloud:
    loadbalancer:
      retry: true
