server:
  port: 8082

spring:
  application:
    name: cliente-mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/clientes_db

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6070/eureka
