server:
  port: 8081

spring:
  application:
    name: cliente-mysql
  datasource:
    url: jdbc:mysql://localhost:3306/clientes_db
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka
